"""initial migration

Revision ID: 4c078d03d146
Revises: None
Create Date: 2016-05-03 09:06:21.039000

"""

# revision identifiers, used by Alembic.
revision = '4c078d03d146'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loginuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('telphone', sa.String(length=30), nullable=True),
    sa.Column('work_unit', sa.String(length=60), nullable=True),
    sa.Column('web_site', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loginuser')
    ### end Alembic commands ###
